// Match venues - FIFA World Cup 2026
var VENUES = {
  1: 'Estadio Azteca, Mexico City',
  2: 'Estadio Akron, Guadalajara',
  3: 'BMO Field, Toronto',
  4: 'SoFi Stadium, Los Angeles',
  5: 'Gillette Stadium, Foxborough',
  6: 'BC Place, Vancouver',
  7: 'MetLife Stadium, East Rutherford',
  8: 'Lumen Field, Seattle',
  9: 'Lincoln Financial Field, Philadelphia',
  10: 'NRG Stadium, Houston',
  11: 'AT&T Stadium, Dallas',
  12: 'Estadio BBVA, Monterrey',
  13: 'Hard Rock Stadium, Miami',
  14: 'Mercedes-Benz Stadium, Atlanta',
  15: 'Lumen Field, Seattle',
  16: 'SoFi Stadium, Los Angeles',
  17: 'Lincoln Financial Field, Philadelphia',
  18: 'BMO Field, Toronto',
  19: 'Hard Rock Stadium, Miami',
  20: 'Levi\'s Stadium, Santa Clara',
  21: 'Gillette Stadium, Foxborough',
  22: 'MetLife Stadium, East Rutherford',
  23: 'NRG Stadium, Houston',
  24: 'Estadio Akron, Guadalajara',
  25: 'Estadio Azteca, Mexico City',
  26: 'BC Place, Vancouver',
  27: 'Lumen Field, Seattle',
  28: 'AT&T Stadium, Dallas',
  29: 'Estadio BBVA, Monterrey',
  30: 'MetLife Stadium, East Rutherford',
  31: 'Estadio Akron, Guadalajara',
  32: 'Lincoln Financial Field, Philadelphia',
  33: 'NRG Stadium, Houston',
  34: 'AT&T Stadium, Dallas',
  35: 'Gillette Stadium, Foxborough',
  36: 'Estadio BBVA, Monterrey',
  37: 'Hard Rock Stadium, Miami',
  38: 'Mercedes-Benz Stadium, Atlanta',
  39: 'SoFi Stadium, Los Angeles',
  40: 'BC Place, Vancouver',
  41: 'MetLife Stadium, East Rutherford',
  42: 'Lincoln Financial Field, Philadelphia',
  43: 'AT&T Stadium, Dallas',
  44: 'Levi\'s Stadium, Santa Clara',
  45: 'Gillette Stadium, Foxborough',
  46: 'NRG Stadium, Houston',
  47: 'NRG Stadium, Houston',
  48: 'Estadio Azteca, Mexico City',
  49: 'Estadio BBVA, Monterrey',
  50: 'Estadio Akron, Guadalajara',
  51: 'BC Place, Vancouver',
  52: 'Lumen Field, Seattle',
  53: 'Estadio Azteca, Mexico City',
  54: 'AT&T Stadium, Dallas',
  55: 'Hard Rock Stadium, Miami',
  56: 'MetLife Stadium, East Rutherford',
  57: 'Levi\'s Stadium, Santa Clara',
  58: 'Mercedes-Benz Stadium, Atlanta',
  59: 'SoFi Stadium, Los Angeles',
  60: 'Lincoln Financial Field, Philadelphia',
  61: 'Gillette Stadium, Foxborough',
  62: 'BMO Field, Toronto',
  63: 'NRG Stadium, Houston',
  64: 'Lumen Field, Seattle',
  65: 'AT&T Stadium, Dallas',
  66: 'Estadio BBVA, Monterrey',
  67: 'Hard Rock Stadium, Miami',
  68: 'Mercedes-Benz Stadium, Atlanta',
  69: 'Estadio Akron, Guadalajara',
  70: 'Estadio Azteca, Mexico City',
  71: 'MetLife Stadium, East Rutherford',
  72: 'BC Place, Vancouver',
}

export function getVenue(matchNumber) {
  return VENUES[matchNumber] || null
}
